title: My Blog
author: jesucristor
email: your-email@domain.com
description:Creando un blog en github pages del curso de Web-Dev-For-Begginers de Microsoft

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
